[package]
name = "ada-url"
authors = ["Yagiz Nizipli <yagiz@nizipli.com>", "Daniel Lemire <daniel@lemire.me>"]
version = "0.1.0"
edition = "2021"
description = "Fast WHATWG Compliant URL parser"
readme = "README.md"
repository = "https://github.com/ada-url/rust"
license = "MIT AND APACHE-2.0"
exclude = [".github"]

[dependencies]
thiserror = "1"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
